version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "weekly"
      day: tuesday
      time: 08:00
      timezone: Europe/Brussels
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: tuesday
      time: 08:00
      timezone: Europe/Brussels
